### ISSUE TITLE
Bug with Inline Button

### ISSUE THREAD

**Issue by sylvestrevgenhiveon** [Telegram-Web-Apps/twa.js#34] opened 2023-05-17 12:08 UTC
**Describe the bug**
When use Inline Mode with button property, and open WebApp from button getting an error "Unable to extract launch params". If we pass the launch params manually in hash url, in example for testing, - getting "components === null" and sdk is not initializing. This bug always appears in MacOS, Android, iOS. Sometimes appears on Web.

**To Reproduce**
1. Add button property to inline_mode with WebApp url
2. Click on button top open WebApp
3. See error

**Expected behavior**
WebApp must open without crashes and SDK must be initialized.

**Comment by heyqbnk** [comment] 2023-05-17 12:13
The problem is inline mode is not passing init data, but SDK always expects it to be

**Comment by heyqbnk** [comment] 2023-07-16 02:09
Fixed in[ `@twa.js/sdk@0.4.5`](https://www.npmjs.com/package/@twa.js/sdk)

**Closed by heyqbnk** 2023-07-16 02:09 UTC
Labels: bug, sdk
